name: Android Release CI

on:
  push:
    tags:
      - "*"
      - "!nightly*"

jobs:
  build:
    name: Build, Sign & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: set up JDK 17
        uses: actions/setup-java@v4.7.0
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - uses: actions/cache@v4.2.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get weather.properties from secrets
        run: printf "%s" "${{ secrets.WEATHER_PROPERTIES }}" > $GITHUB_WORKSPACE/weather.properties

      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew assembleWithInternetRelease && ./gradlew assembleWithoutInternetRelease

      - name: Sign APK - WithInternet
        uses: ilharp/sign-android-release@v1.0.4
        # ID used to access action output
        id: sign_app_withInternet
        with:
          releaseDir: app/build/outputs/apk/withInternet/release
          signingKey: ${{ secrets.SIGNINGKEY_BASE64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Release to GitHub - WithInternet
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.sign_app_withInternet.outputs.signedFile}}
          asset_name: EasyLauncher-Internet-${{ github.ref_name }}-Signed.apk
          tag: ${{ github.ref }}
          overwrite: true

      - name: Sign APK - WithoutInternet
        uses: ilharp/sign-android-release@v1.0.4
        # ID used to access action output
        id: sign_app_withoutInternet
        with:
          releaseDir: app/build/outputs/apk/withoutInternet/release
          signingKey: ${{ secrets.SIGNINGKEY_BASE64 }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 35.0.0

      - name: Release to GitHub  - WithoutInternet
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.sign_app_withoutInternet.outputs.signedFile}}
          asset_name: EasyLauncher-${{ github.ref_name }}-Signed.apk
          tag: ${{ github.ref }}
          overwrite: true
